# Generated by Django 4.1.8 on 2025-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0002_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='msg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义内容'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='status',
            field=models.BooleanField(default=True, help_text='响应状态', verbose_name='响应状态'),
        ),
    ]
