# Generated by Django 4.1.8 on 2025-06-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0003_loginlog_msg_loginlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='data_scope',
        ),
        migrations.RemoveField(
            model_name='role',
            name='dept',
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='field',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='menu_field_permission', to='mysystem.menufield', verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='menubutton',
            name='menu',
            field=models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='menu_buttons', to='mysystem.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='menufield',
            name='menu',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='menu_fields', to='mysystem.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='menufield',
            name='model',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='所属模型Model'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='data_scope',
            field=models.SmallIntegerField(choices=[(0, '仅本人数据权限'), (1, '本部门数据权限'), (2, '本部门及以下数据权限'), (3, '自定义部门数据权限'), (4, '全部数据权限'), (5, '同全局数据权限')], default=3, help_text='数据权限', verbose_name='数据权限'),
        ),
    ]
