# Generated by Django 4.1.8 on 2025-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0004_remove_role_data_scope_remove_role_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemenupermission',
            name='data_scope',
            field=models.SmallIntegerField(choices=[(0, '仅本人数据权限'), (1, '本部门数据权限'), (2, '本部门及以下数据权限'), (3, '自定义部门数据权限'), (4, '全部数据权限'), (5, '同全局数据权限')], default=4, help_text='数据权限', verbose_name='数据权限'),
        ),
        migrations.AddField(
            model_name='rolemenupermission',
            name='dept',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='数据权限-关联部门', to='mysystem.dept', verbose_name='数据权限-关联部门'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='data_scope',
            field=models.SmallIntegerField(choices=[(0, '仅本人数据权限'), (1, '本部门数据权限'), (2, '本部门及以下数据权限'), (3, '自定义部门数据权限'), (4, '全部数据权限'), (5, '同全局数据权限')], default=5, help_text='数据权限', verbose_name='数据权限'),
        ),
    ]
