# Generated by Django 4.1.8 on 2025-06-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0005_rolemenupermission_data_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='role_field_permission', to='mysystem.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='rolemenubuttonpermission',
            name='role',
            field=models.ForeignKey(db_constraint=False, help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_button_permission', to='mysystem.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu',
            field=models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='menu_permission', to='mysystem.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='role',
            field=models.ForeignKey(db_constraint=False, help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_permission', to='mysystem.role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='用户昵称', max_length=100, null=True, verbose_name='用户昵称'),
        ),
    ]
