# Generated by Django 4.1.8 on 2025-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0006_alter_fieldpermission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='creator_name',
            field=models.CharField(blank=True, help_text='操作人', max_length=30, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, '未知'), (1, '女'), (2, '男')], default=0, help_text='性别', null=True, verbose_name='性别'),
        ),
    ]
