# Generated by Django 4.1.8 on 2025-07-05 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0007_operationlog_creator_name_alter_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('target_type', models.SmallIntegerField(default=0, verbose_name='目标类型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dept', models.ManyToManyField(blank=True, db_constraint=False, to='mysystem.dept', verbose_name='关联部门')),
                ('role', models.ManyToManyField(blank=True, db_constraint=False, to='mysystem.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'db_table': 'lyadmin_message',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='code',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='name',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='label',
            field=models.CharField(blank=True, help_text='字典名称', max_length=100, null=True, verbose_name='字典名称'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='value',
            field=models.CharField(blank=True, help_text='字典编号/实际值', max_length=200, null=True, verbose_name='字典编号'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='父级', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sublist', to='mysystem.dictionary', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='status',
            field=models.BooleanField(default=True, help_text='状态', verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('notification', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='mysystem.notification', verbose_name='关联消息')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户表')),
            ],
            options={
                'verbose_name': '消息用户',
                'verbose_name_plural': '消息用户',
                'db_table': 'lyadmin_message_users',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='notifications_users', through='mysystem.NotificationUsers', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
