# Generated by Django 4.1.8 on 2025-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0009_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag_type',
            field=models.SmallIntegerField(choices=[(0, '平台公告'), (1, '按用户'), (2, '按部门'), (3, '按角色')], default=0, verbose_name='标签类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.SmallIntegerField(choices=[(0, '平台公告'), (1, '按用户'), (2, '按部门'), (3, '按角色')], default=0, verbose_name='目标类型'),
        ),
    ]
