# Generated by Django 4.1.8 on 2025-07-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0010_notification_tag_type_alter_notification_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationusers',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否逻辑删除', verbose_name='是否逻辑删除'),
        ),
    ]
